# Generated by Django 5.2.7 on 2025-12-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('author_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('afiliasi', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('total_sitasi', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('i10_index', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=500)),
                ('link_jurnal', models.URLField(blank=True, max_length=500, null=True)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('nama_jurnal', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun', models.CharField(blank=True, max_length=10, null=True)),
                ('jumlah_sitasi', models.IntegerField(default=0)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publikasi', to='app.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='StatistikSitasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('jumlah', models.IntegerField(default=0)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistik', to='app.dosen')),
            ],
            options={
                'ordering': ['tahun'],
            },
        ),
    ]
