# Generated by Django 5.2.7 on 2025-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='bidang_minat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
