# Generated by Django 5.2.7 on 2025-12-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dosen_bidang_minat_dosen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='h_index_sejak_2020',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dosen',
            name='i10_index_sejak_2020',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dosen',
            name='total_sitasi_sejak_2020',
            field=models.IntegerField(default=0),
        ),
    ]
