# Generated by Django 5.2.7 on 2026-01-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dosen_h_index_sejak_2020_dosen_i10_index_sejak_2020_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='fakultas',
            field=models.CharField(choices=[('FEB', 'Fakultas Ekonomi & Bisnis'), ('FTD', 'Fakultas Teknik & Desain')], default='FTD', max_length=3),
        ),
    ]
